import Head from 'next/head' 
import Product_listing_page from '@/Components/Product_listing_page'
import { Product } from '@/type'
// const inter = inter({ subsets: ['latin'] })
interface Props{
  productData:Product
}
export default function Home({productData}:Props) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Product_listing_page productData={productData}></Product_listing_page>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossOrigin="anonymous"></script>
      </main>
    </>
  )
}

// =========== SSR data fetching =======================

export const getServerSideProps = async ()=>{
  const productData = await (await fetch('http://localhost:3000/api/productdata')).json();
  return {
    props:{productData},
  }
}
