import Head from 'next/head' 
import Script from 'next/script'
import Product_listing_page from '@/Components/Product_listing_page'
import { Product } from '@/type'
// const inter = inter({ subsets: ['latin'] })
import { useEffect } from 'react'
import { useSession } from 'next-auth/react'
import { addUser, removeUser } from '@/redux/shoperSlice';
import { useDispatch } from 'react-redux'
interface Props{
  productData:Product
}
export default function Home({productData}:Props) {
  const dispatch = useDispatch();
  const {data:session} = useSession();
  useEffect(()=>{
    if(session){
      dispatch(addUser({
        name:session.user?.name,
        email:session.user?.email,
        image:session.user?.image
      }))
    }
    else {
        dispatch(removeUser());
    }
},[session,dispatch]);
  return (
    <>
      <Head>
        <title>Next Js P1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Product_listing_page productData={productData}></Product_listing_page>
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossOrigin="anonymous"></Script>
      </main>
    </>
  )
}

// =========== SSR data fetching =======================

export const getServerSideProps = async ()=>{
  const productData = await (await fetch('https://radhe-ecom-web.vercel.app/api/productdata')).json();
  return {
    props:{productData},
  }
}
